Repository Solome6/Project-Atlas, pull requests merged in 2021-02, with the labels that each got.

#10 Updated package versioning
  atlas-extension/project-atlas/package-lock.json
  atlas-extension/project-atlas/package.json
  atlas-extension/project-atlas/src/extension.ts
  atlas-extension/project-atlas/src/test/extension.spec.ts
  atlas-extension/project-atlas/tsconfig.json
Labels: upgrade

#13 Closes #11 - Added JSON caching
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  atlas-extension/project-atlas/.vscode/extensions.json
  atlas-extension/project-atlas/.vscode/launch.json
  atlas-extension/project-atlas/.vscode/settings.json
  atlas-extension/project-atlas/.vscode/tasks.json
  atlas-extension/project-atlas/src/extension.ts
  atlas-extension/project-atlas/src/messaging.ts
  atlas-extension/project-atlas/src/scripts/uiControls.ts
  atlas-extension/project-atlas/src/services/fs.service.ts
  atlas-extension/project-atlas/src/services/parser.service.ts
  mocks/Atlas-Mock/Atlas-Mock.iml
  mocks/Atlas-Mock/src/example_project/controller/PersonDogController.java
  mocks/Atlas-Mock/src/example_project/models/Cat.java
  mocks/Atlas-Mock/src/example_project/models/Corgi.java
  mocks/Atlas-Mock/src/example_project/models/Dog.java
  mocks/Atlas-Mock/src/example_project/models/Person.java
  mocks/Atlas-Mock/src/example_project/models/Pet.java
  mocks/Atlas-Mock/src/example_project/views/DogView.java
  mocks/Atlas-Mock/src/example_project/views/PetRelationshipView.java
  mocks/BAD_example_project/src/controllers/PersonDogController.java
  mocks/BAD_example_project/src/models/Cat.java
  mocks/BAD_example_project/src/models/Corgi.java
  mocks/BAD_example_project/src/models/Dog.java
  mocks/BAD_example_project/src/models/Person.java
  mocks/BAD_example_project/src/models/Pet.java
  mocks/BAD_example_project/src/views/DogView.java
  mocks/BAD_example_project/src/views/PetRelationshipView.java
Labels: new feature

#14 Add Documentation
  READEME.md
  atlas-extension/README.md
  atlas-extension/project-atlas/tsconfig.json
  atlas-logo.png
  atlas/README.md
  atlas/src/main/java/atlas/groups/DirectoryGroup.java
  atlas/src/main/java/atlas/groups/ExpressionGroup.java
  atlas/src/main/java/atlas/groups/FieldGroup.java
  atlas/src/main/java/atlas/groups/FileGroup.java
  atlas/src/main/java/atlas/groups/FunctionGroup.java
  atlas/src/main/java/atlas/groups/IExpressionParentGroup.java
  atlas/src/main/java/atlas/groups/IReferencer.java
Labels: documentation
